spring:
  application:
    name: hotel_project
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-container:3306/testdb
    username: root
    password: 1234

  mustache:
    suffix: .html
    servlet:
      cache: false

  jpa:
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.hotel_project
  configuration:
    map-underscore-to-camel-case: true
