spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:13306/booking_db?allowPublicKeyRetrieval=true
    username: book_user
    password: book_1234

  mustache:
    suffix: .html
    servlet:
      cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.hotel_project
  configuration:
    map-underscore-to-camel-case: true
